### PR TITLE
Add benchmark on collection load time

### PR DESCRIPTION
**Pull request by tellet-q**
* Introduce BENCHMARK_STRATEGY env variable to control the experiments, possible values: `default` | `tenants` | `collection-reload`
* Add a new server config `qdrant-continuous-benchmarks-snapshot` with `QDRANT_NUM_CPUS: 4` to ensure no optimizations are triggered after snapshot recovery
* Add a new column `collection_load_time_ms` into database. Fetch the value from /telemetry response.

Prepare snapshots for cases,  upload them to [GCP](https://console.cloud.google.com/storage/browser/qdrant-benchmark-snapshots/all-payloads?pageState=(%22StorageObjectListTable%22:(%22f%22:%22%255B%255D%22))&authuser=0&project=key-surf-337615):
* 500k points with all possible payloads, 768x, all default values
* 500k points with all possible payloads, 768x, on_disk:true (all possible on_disk places)
* 500k points with all possible payloads, sparse vectors, all default values
* 500k points with all possible payloads, sparse vectors, on_disk:true (all possible on_disk places)

### CODE REVIEW

**Comment by tellet-q** [comment]
Example run: https://github.com/qdrant/vector-db-benchmark/actions/runs/11033744818

**Comment by tellet-q** [comment]
@KShivendu @generall I wanted to run the runLoadTimeBenchmark job in parallel almost everything in code is ready, but it not possible since the 2nd server has ARM architecture and we don't have Docker images for ARM.

**Comment by tellet-q** [comment]
I updated the code to run the benchmark in parallel with tenants benchmark. The benchmark runs in a separate server machine and only the client machine is shared.

https://github.com/qdrant/vector-db-benchmark/actions/runs/11051637232

**Review by KShivendu — APPROVED** [review]
LGTM. I saw that you updated the dashboard as well. Great!

**Pull request merged**
