### PR TITLE
set ports instead of network_mode

### PR DESCRIPTION
**Pull request by ekorman**
the docker compose files which use `network_mode: host` currently do not work on systems such as macos where docker uses a VM, causing `run.py` to error. this PR explicitly sets the ports

### CODE REVIEW

**Comment by KShivendu** [comment]
Nice catch. Thanks for creating the PR. 

Can you please check other engines as well and update the PR if required? :)

**Comment by ekorman** [comment]
> Nice catch. Thanks for creating the PR.
> 
> Can you please check other engines as well and update the PR if required? :)

@KShivendu i just went through them and weaviate also needed an update. just pushed and its working for me now.

**Comment by LukasWestholt** [comment]
I really need this too!

**Comment by LukasWestholt** [comment]
Can you look on it again @KShivendu ?

**Comment by KShivendu** [comment]
> I really need this too!

Merged. Thanks for asking. 

Ps. You can always checkout the branch and runs it anyways :)

**Review by KShivendu — APPROVED** [review]

**Pull request merged**
